AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cognito-sample
  Example SAM project creating some basic user functionality with Cognito. 
  
Globals:
  Function:
    Timeout: 3

Resources:
  RegisterCreateAccountFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/account/register
      Handler: index.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /account
            Method: put
  
  ## =====================================
  ##          Cognito
  ## =====================================
  
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 100
      Schema:
        - AttributeDataType: String
          Name: FullName
        - AttributeDataType: String
          Name: Birthday

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RegisterCreateAccountFunction.Arn
