AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cognito-sample
  Example SAM project creating some basic user functionality with Cognito. 
  
Globals:
  Function:
    Timeout: 3
    Layers:
      - !Ref BaseLayer
    Environment:
      Variables:
        APP_REGION: "eu-west-1"
        APP_LOG_LEVEL: "info"

Resources:
  RegisterCreateAccountFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/account/register
      Handler: index.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          APP_USERPOOL_CLIENT_ID: !Ref CognitoUserPoolClient
      Events:
        RegisterAccount:
          Type: Api
          Properties:
            Path: /account
            Method: put
  
  ConfirmUserAccountFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/account/confirm
      Handler: index.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          APP_USERPOOL_CLIENT_ID: !Ref CognitoUserPoolClient
      Events:
        ConfirmAccount:
          Type: Api
          Properties:
            Path: /account/confirm
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/account/login
      Handler: index.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          APP_USERPOOL_CLIENT_ID: !Ref CognitoUserPoolClient
      Events:
        Login:
          Type: Api
          Properties:
            Path: /account/login
            Method: post

  ## =====================================
  ##          Layers
  ## =====================================

  BaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: base-layer
      Description: Dependencies for Cognito
      ContentUri: src/layers/base/
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: "MIT"
      RetentionPolicy: Retain

  ## =====================================
  ##          Cognito
  ## =====================================
  
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: false
          TemporaryPasswordValidityDays: 100
      Schema:
        - AttributeDataType: String
          Name: FullName
        - AttributeDataType: String
          Name: Birthday

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${CognitoUserPool}-client
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt RegisterCreateAccountFunction.Arn
